name: Notify Parent Submodules

on:
  push:
    branches: [ v2.24.0 ]

jobs:
  notify:
    uses: KEPM-PGSEnergy/github-workflows/.github/workflows/notify-parent-submodules.yml@main
    with:
      parent-repos-json: '["KEPM-PGSEnergy/lin_apk_tx_rx", "KEPM-PGSEnergy/lin_upza_dfz", "KEPM-PGSEnergy/lin_ars"]'
    secrets:
      pat-token: ${{ secrets.PAT_ACTIONS }}
